builder:
  track: stable

labels:
  app: tslint-config-travix
  team: origami
  language: nodejs

stages:
  release:
    image: scardon/ruby-node-alpine
    env:
      NPM_AUTH_TOKEN: estafette.secret(TRyywCkeoelfgARr.jtg-Hx3Wh678ZCWOocOCy1uk-XQYt2dE44RunaOSX2WftRsBxTz3my13Ljr6evWQncACiQ==)
      GITHUB_API_TOKEN: estafette.secret(hmZThAIN98k-1Cyd.YIRA_g9iZeaNzQT39xWuH0o4_kwizQTO0ysC54kMQ95YvxRvt3vthzsFrfpQPwoCHb_rDy7K2F4=)
      NPM_PACKAGE_VERSION: 'patch'
      GIT_USER_NAME: 'Yuri Drabik'
      GIT_USER_EMAIL: 'yurist38@mail.ru'
      CHANGELOG_COMMIT_MESSAGE: 'Update changelog'
    commands:
      - apk --no-cache add git python make
      - if [ "$(git log -1 --pretty=%B)" == "${CHANGELOG_COMMIT_MESSAGE}" ]; then exit 0; fi # we don't need to release if last commit was a changelog
      - npm install
      - gem install github_changelog_generator
      - git config user.name "${GIT_USER_NAME}"
      - git config user.email "${GIT_USER_EMAIL}"
      - git checkout master
      - git pull
      - npm version ${NPM_PACKAGE_VERSION}
      - npm publish
      - github_changelog_generator -t ${GITHUB_API_TOKEN}
      - git add CHANGELOG.md
      - git commit -m "${CHANGELOG_COMMIT_MESSAGE}"
      - git push --follow-tags
    when:
      status == 'succeeded' &&
      server == 'gocd' &&
      branch == 'master'

