builder:
  track: stable

labels:
  app: tslint-config-travix
  team: origami
  language: nodejs

stages:
  publish:
    image: scardon/ruby-node-alpine
    commands:
      - apk --no-cache add git python make
      # - export NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
      # - export NPM_PACKAGE_VERSION=${NPM_PACKAGE_VERSION}
      - npm install
      - gem install github_changelog_generator
      # - git remote rm origin
      # - git remote add origin https://${GITHUB_API_TOKEN}:x-oauth-basic@github.com/Travix-International/tslint-config-travix
      - make release
      # - make changelog
      # - make push-changelog
    when:
      status == 'succeeded' &&
      server == 'gocd' &&
      branch == 'master'

