builder:
  track: stable

labels:
  app: tslint-config-travix
  team: origami
  language: nodejs

stages:
  publish:
    image: scardon/ruby-node-alpine
    env:
      NPM_AUTH_TOKEN: ${NPM_AUTH_TOKEN}
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      NPM_PACKAGE_VERSION: ${NPM_PACKAGE_VERSION}
    commands:
      - apk --no-cache add git python make
      - npm install
      - gem install github_changelog_generator
      - make release
      # - make changelog
      # - make push-changelog
    when:
      status == 'succeeded' &&
      server == 'gocd' &&
      branch == 'master'

