builder:
  track: stable

labels:
  app: tslint-config-travix
  team: origami
  language: nodejs

stages:
  publish:
    image: starefossen/ruby-node
    commands:
      - apk --no-cache add git python
      - npm install
      - gem install github_changelog_generator
      - make release
      - make changelog
      - make push-changelog
    when:
      status == 'succeeded' &&
      server == 'gocd' &&
      branch == 'master'

