builder:
  track: stable

labels:
  app: tslint-config-travix
  team: origami
  language: nodejs

stages:
  publish:
    image: node:8-alpine
    commands:
      - apk --no-cache add git python ruby-dev
      - npm install
      - gem install github_changelog_generator
      - make release
      - make changelog
      - make push-changelog

