builder:
  track: stable

labels:
  app: tslint-config-travix
  team: origami
  language: nodejs

stages:
  publish:
    image: scardon/ruby-node-alpine
    commands:
      - apk --no-cache add git python make
      - echo "NPM_TOKEN: ${NPM_AUTH_TOKEN}"
      - env
      - export NPM_PACKAGE_VERSION=$NPM_PACKAGE_VERSION
      - npm install
      - gem install github_changelog_generator
      - make release
      # - make changelog
      # - make push-changelog
    when:
      status == 'succeeded' &&
      server == 'gocd' &&
      branch == 'master'

