builder:
  track: stable

labels:
  app: tslint-config-travix
  team: origami
  language: nodejs

stages:
  release:
    image: scardon/ruby-node-alpine
    env:
      NPM_AUTH_TOKEN: estafette.secret(TRyywCkeoelfgARr.jtg-Hx3Wh678ZCWOocOCy1uk-XQYt2dE44RunaOSX2WftRsBxTz3my13Ljr6evWQncACiQ==)
      GITHUB_API_TOKEN: estafette.secret(hmZThAIN98k-1Cyd.YIRA_g9iZeaNzQT39xWuH0o4_kwizQTO0ysC54kMQ95YvxRvt3vthzsFrfpQPwoCHb_rDy7K2F4=)
      NPM_PACKAGE_VERSION: 'patch'
    commands:
      - apk --no-cache add git python make
      - npm install
      - gem install github_changelog_generator
      - make release
      # - make changelog
      # - make push-changelog
    when:
      status == 'succeeded' &&
      server == 'gocd' &&
      branch == 'master'

